CREATE DATABASE IF NOT EXISTS bios_db;
USE bios_db;

CREATE TABLE STUDENT (
	`userID` VARCHAR(100) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`school` VARCHAR(100) NOT NULL,
	`edollar` DECIMAL (10,2) NOT NULL,
PRIMARY KEY (`userID`)
);

CREATE TABLE ADMIN (
	`adminID` VARCHAR(100) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
PRIMARY KEY (`adminID`)
);


CREATE TABLE COURSE (
	`course` VARCHAR(100) NOT NULL,
	`school` VARCHAR(100) NOT NULL,
	 `title` VARCHAR(100) NOT NULL,
	`description` VARCHAR(3000) NOT NULL,
	`examdate` VARCHAR(100) NOT NULL,
	`exam_start` VARCHAR(100) NOT NULL,	
	`exam_end` VARCHAR(100) NOT NULL,
PRIMARY KEY (`course`)
);


CREATE TABLE SECTION (
	`course` VARCHAR(100) NOT NULL,
	`section` VARCHAR(100) NOT NULL,
	`day` int NOT NULL,
	`start` VARCHAR(100)  NOT NULL,
	`end` VARCHAR(100)  NOT NULL,
	`instructor` VARCHAR(100) NOT NULL,	
	`venue` VARCHAR(100) NOT NULL,
	`size` INT NOT NULL,
PRIMARY KEY (`course`, `section`),
CONSTRAINT SECTION_FK1 FOREIGN KEY (course) REFERENCES COURSE (course) 
);


CREATE TABLE PREREQUISITE (
	`course` VARCHAR(100) NOT NULL,
	`prerequisite` VARCHAR(100) NOT NULL,
PRIMARY KEY (`course`, `prerequisite`),
CONSTRAINT `PREREQUISITE_FK1` FOREIGN KEY (`course`) REFERENCES `COURSE` (`course`) ,
CONSTRAINT `PREREQUISITE_FK2` FOREIGN KEY (`prerequisite`) REFERENCES `COURSE` (`course`) 
);


CREATE TABLE COURSE_COMPLETED (
	`userID` VARCHAR(100) NOT NULL,
	`code` VARCHAR(100) NOT NULL,
PRIMARY KEY (`userID`, `code`),
CONSTRAINT `COURSE_COMPLETED_FK1` FOREIGN KEY (`userID`) REFERENCES `STUDENT` (`userID`) ,
CONSTRAINT `COURSE_COMPLETED_FK2` FOREIGN KEY (`code`) REFERENCES `COURSE` (`course`) 
);

CREATE TABLE BID (
	`userID` VARCHAR(100) NOT NULL,
	`amount` DECIMAL (10,2) NOT NULL,
	`code` VARCHAR(100) NOT NULL,
	`section` VARCHAR(100) NOT NULL,
PRIMARY KEY (`userID`, `code`),
CONSTRAINT `BID_FK1` FOREIGN KEY (`userID`) REFERENCES `STUDENT` (`userID`) ,
CONSTRAINT `BID_FK2` FOREIGN KEY (`code`) REFERENCES `COURSE` (`course`) 
);

CREATE TABLE SECTION_STUDENT (
	`userID` VARCHAR(100) NOT NULL,
	`course` VARCHAR(100) NOT NULL,
	`section` VARCHAR(100) NOT NULL,
	`amount` DECIMAL (10, 2) ,
PRIMARY KEY (`userID`, `course`, `section`),
CONSTRAINT `SECTION_STUDENT_FK1` FOREIGN KEY (`userID`) REFERENCES `STUDENT` (`userID`) ,
#CONSTRAINT `SECTION_STUDENT_FK2` FOREIGN KEY (`course`) REFERENCES `COURSE` (`course`) ,
CONSTRAINT `SECTION_STUDENT_FK3` FOREIGN KEY (`course`, `section`) REFERENCES `SECTION` (`course`, `section`) 
);

CREATE TABLE SECTION_STUDENT_ROUND2 (
	`userID` VARCHAR(100) NOT NULL,
	`course` VARCHAR(100) NOT NULL,
	`section` VARCHAR(100) NOT NULL,
	`amount` DECIMAL (10, 2) ,
PRIMARY KEY (`userID`, `course`, `section`));
